routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/login/{lang?}', 'Auth\LoginController@showLoginForm')->name('login');

Route::get('/password/resets/{lang?}', 'Auth\LoginController@showLinkRequestForm')->name('change.langPass');

Route::get(
    '/', [
           'as' => 'dashboard',
           'uses' => 'DashboardController@index',
       ]
)->middleware(
    [
        'XSS',
    ]
);
Route::get(
    '/dashboard', [
                    'as' => 'dashboard',
                    'uses' => 'DashboardController@index',
                ]
)->middleware(
    [

        'XSS',
        'auth',
    ]
);

Route::group(['middleware' => ['auth', 'XSS']], function (){
    Route::get('change-language/{lang}', 'LanguageController@changeLanquage')->name('change.language')->middleware(['auth', 'XSS']);
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language')->middleware(['auth', 'XSS']);
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data')->middleware(['auth', 'XSS']);
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language')->middleware(['auth', 'XSS']);
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language')->middleware(['auth', 'XSS']);

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy')->middleware(['auth', 'XSS']);
});

Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ], function (){
    Route::resource('stores', 'StoreController');
    Route::post('store-setting/{id}', 'StoreController@savestoresetting')->name('settings.store');
}
);
Route::get('change-language-store/{slug?}/{lang}', 'LanguageController@changeLanquageStore')->name('change.languagestore')->middleware(['XSS']);
Route::get('/change/mode',['as' => 'change.mode','uses' =>'DashboardController@changeMode']);

Route::get('profile', 'DashboardController@profile')->name('profile')->middleware(
    [
        'auth',
        'XSS',
    ]
);
Route::put('change-password', 'DashboardController@updatePassword')->name('update.password');
Route::put('edit-profile', 'DashboardController@editprofile')->name('update.account')->middleware(
    [
        'auth',
        'XSS',
    ]
);


Route::get('storeanalytic', 'StoreAnalytic@index')->middleware('auth')->name('storeanalytic')->middleware(['XSS']);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::post('business-setting', 'SettingController@saveBusinessSettings')->name('business.setting');
    Route::post('company-setting', 'SettingController@saveCompanySettings')->name('company.setting');
    Route::post('email-setting', 'SettingController@saveEmailSettings')->name('email.setting');
    Route::post('system-setting', 'SettingController@saveSystemSettings')->name('system.setting');
    Route::post('pusher-setting', 'SettingController@savePusherSettings')->name('pusher.setting');
    Route::get('test-mail', 'SettingController@testMail')->name('test.mail');
    Route::post('test-mail', 'SettingController@testSendMail')->name('test.send.mail');
    Route::get('settings', 'SettingController@index')->name('settings');
    Route::post('payment-setting', 'SettingController@savePaymentSettings')->name('payment.setting');
    Route::post('owner-payment-setting/{id}', 'SettingController@saveOwnerPaymentSettings')->name('owner.payment.setting');
    Route::post('owner-email-setting/{slug?}', 'SettingController@saveOwneremailSettings')->name('owner.email.setting');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('product_categorie', 'ProductCategorieController');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('product_tax', 'ProductTaxController');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('shipping', 'ShippingController');
}
);
Route::resource('location', 'LocationController')->middleware(['auth', 'XSS']);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('orders', 'OrderController');
}
);
Route::group(
    [
        'middleware' => [
            'XSS',
        ],
    ], function (){
    Route::resource('rating', 'RattingController');
    Route::post('rating_view', 'RattingController@rating_view')->name('rating.rating_view');
    Route::get('rating/{slug?}/product/{id}', 'RattingController@rating')->name('rating');
    Route::post('stor_rating/{slug?}/product/{id}', 'RattingController@stor_rating')->name('stor_rating');
    Route::post('edit_rating/product/{id}', 'RattingController@edit_rating')->name('edit_rating');
}
);
Route::group(
    [
        'middleware' => [
            'XSS',
        ],
    ], function (){
    Route::resource('subscriptions', 'SubscriptionController');
    Route::POST('subscriptions/{id}', 'SubscriptionController@store_email')->name('subscriptions.store_email');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::get('/product-variants/create',['as' => 'product.variants.create','uses' =>'ProductController@productVariantsCreate']);
    Route::get('/get-product-variants-possibilities',['as' => 'get.product.variants.possibilities','uses' =>'ProductController@getProductVariantsPossibilities']);
    Route::get('product/grid', 'ProductController@grid')->name('product.grid');
    Route::resource('product', 'ProductController');
    Route::delete('product/{id}/delete', 'ProductController@fileDelete')->name('products.file.delete');
    Route::post('product/{id}/update', 'ProductController@productUpdate')->name('products.update');
}
);
Route::get('get-products-variant-quantity',['as' => 'get.products.variant.quantity','uses' =>'ProductController@getProductsVariantQuantity']);
Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ], function (){
    //    Route::get('store-grid/grid', 'StoreController@grid')->name('store-grid.grid');
    Route::resource('store-resource', 'StoreController');
}
);
Route::get('/store-change/{id}','StoreController@changeCurrantStore')->name('change_store')->middleware(['auth','XSS']);


Route::get('store/{slug?}', 'StoreController@storeSlug')->name('store.slug');
Route::get('user-cart-item/{slug?}/cart', 'StoreController@StoreCart')->name('store.cart');
Route::get('user-address/{slug?}/useraddress', 'StoreController@userAddress')->name('user-address.useraddress');
Route::get('store-payment/{slug?}/userpayment', 'StoreController@userPayment')->name('store-payment.payment');
Route::get('store/{slug?}/product/{id}', 'StoreController@productView')->name('store.product.product_view');
Route::post('user-product_qty/{slug?}/product/{id}/{variant_id?}', 'StoreController@productqty')->name('user-product_qty.product_qty');
Route::post('customer/{slug}', 'StoreController@customer')->name('store.customer');
Route::post('user-location/{slug}/location/{id}', 'StoreController@UserLocation')->name('user.location');
Route::post('user-shipping/{slug}/shipping/{id}', 'StoreController@UserShipping')->name('user.shipping');
Route::post('save-rating/{slug}', 'StoreController@saverating')->name('store.saverating');
Route::delete('delete_cart_item/{slug}/product/{id}/{team_member?}/{variant_id?}', 'StoreController@delete_cart_item')->name('delete.cart_item');

Route::get('store-complete/{slug?}/{id}', 'StoreController@complete')->name('store-complete.complete');

Route::post('add-to-cart/{slug?}/{id}/{variant_id?}', 'StoreController@addToCart')->name('user.addToCart');
Route::DELETE('ownerstore-delete/{id}', 'StoreController@ownerstoredestroy')->name('ownerstore.destroy');

Route::get('getMembers/{slug}', 'StoreController@getMembers')->name('user.getMembers');
Route::post('saveMember/{slug}', 'StoreController@storeMember')->name('user.storeMember');

Route::post('payment-setting', 'SettingController@savePaymentSettings')->name('payment.setting');

Route::group(['middleware' => ['XSS']], function (){
    Route::get('order', 'StripePaymentController@index')->name('order.index');
    Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe');
    Route::post('/stripe/{slug?}', 'StripePaymentController@stripePost')->name('stripe.post');
});

Route::post('pay-with-paypal/{slug?}', 'PaypalController@PayWithPaypal')->name('pay.with.paypal')->middleware(['XSS']);

Route::get('{id}/get-payment-status{slug?}', 'PaypalController@GetPaymentStatus')->name('get.payment.status')->middleware(['XSS']);

Route::get('{slug?}/order/{id}', 'StoreController@userorder')->name('user.order');

Route::post('{slug?}/whatsapp', 'StoreController@whatsapp')->name('user.whatsapp');
Route::post('{slug?}/cod', 'StoreController@cod')->name('user.cod');
Route::post('{slug?}/bank_transfer', 'StoreController@bank_transfer')->name('user.bank_transfer');

Route::get('qr-code', function () {
    return QrCode::generate();
});

app/Shipping.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shipping extends Model
{
    protected $fillable = [
        'name',
        'price',
        'location_id',
        'store_id',
        'created_by',
    ];

    public function locationName()
    {
        $result =  Location::whereIn('id',explode(',',$this->location_id))->get()->pluck('name')->toArray();
        return implode(', ',$result);
    }
}

app/Http/Controllers/ShippingController.php
<?php

namespace App\Http\Controllers;

use App\Location;
use App\Shipping;
use App\Store;
use Illuminate\Http\Request;
use function Psy\sh;

class ShippingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = \Auth::user()->current_store;

        $shippings = Shipping::where('store_id', $user)->where('created_by', \Auth::user()->creatorId())->get();
        $locations = Location::where('store_id', $user)->where('created_by', \Auth::user()->creatorId())->get();

        return view('shipping.index', compact('shippings', 'locations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $locations = Location::get()->pluck('name', 'id');

        return view('shipping.create', compact('locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(
            $request, [
                        'name' => 'required|max:40',
                        'price' => 'required|numeric',
                    ]
        );

        $shipping              = new Shipping();
        $shipping->name        = $request->name;
        $shipping->price       = $request->price;
        $shipping->location_id = implode(',', $request->location);
        $shipping->store_id    = \Auth::user()->current_store;
        $shipping->created_by  = \Auth::user()->creatorId();
        $shipping->save();

        return redirect()->back()->with('success', 'Shipping' . $shipping->name . ' added!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Shipping $shipping
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Shipping $shipping)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Shipping $shipping
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Shipping $shipping)
    {
        $locations = Location::get()->pluck('name', 'id');

        return view('shipping.edit', compact('shipping', 'locations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Shipping $shipping
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Shipping $shipping)
    {
        $this->validate(
            $request, [
                        'name' => 'required|max:40',
                        'price' => 'required|numeric',
                    ]
        );

        $shipping->name        = $request->name;
        $shipping->price       = $request->price;
        $shipping->location_id = implode(',', $request->location);
        $shipping->created_by  = \Auth::user()->creatorId();
        $shipping->save();

        return redirect()->back()->with('success', 'Shipping' . $shipping->name . ' Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Shipping $shipping
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy(Shipping $shipping)
    {

        $shipping->delete();

        return redirect()->back()->with('success', 'Shipping ' . $shipping->name . ' Deleted!');
    }
}

resources/views/shipping/create.blade.php
{{Form::open(array('url'=>'shipping','method'=>'post'))}}
<div class="row">
    <div class="col-12">
        <div class="form-group">
            {{Form::label('name',__('Name'),array('class'=>'form-control-label')) }}
            {{Form::text('name',null,array('class'=>'form-control','placeholder'=>__('Enter Name'),'required'=>'required'))}}
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            {{Form::label('price',__('Price'),array('class'=>'form-control-label')) }}
            {{Form::text('price',null,array('class'=>'form-control','placeholder'=>__('Enter Price'),'required'=>'required'))}}
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            {{Form::label('Location',__('Location'),array('class'=>'form-control-label')) }}
            {!! Form::select('location[]', $locations, null,array('class' => 'form-control','data-toggle'=>'select','multiple')) !!}
        </div>
    </div>
    <div class="w-100 text-right">
        {{Form::submit(__('Save'),array('class'=>'btn btn-sm btn-primary rounded-pill mr-auto'))}}
    </div>
</div>
{{Form::close()}}

resources/views/shipping/edit.blade.php
{{Form::model($shipping, array('route' => array('shipping.update', $shipping->id), 'method' => 'PUT')) }}
<div class="row">
    <div class="col-12">
        <div class="form-group">
            {{Form::label('name',__('Name'))}}
            {{Form::text('name',null,array('class'=>'form-control','placeholder'=>__('Enter Product Category')))}}
            @error('name')
            <span class="invalid-name" role="alert">
                    <strong class="text-danger">{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="col-12">
        <div class="form-group">
            {{Form::label('price',__('Price'))}}
            {{Form::text('price',null,array('class'=>'form-control','placeholder'=>__('Enter State Name')))}}
            @error('price')
            <span class="invalid-price" role="alert">
                    <strong class="text-danger">{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
    <div class="col-12">
        <div class="form-group ">
            {{Form::label('location',__('Location'),array('class'=>'form-control-label')) }}
            {!! Form::select('location[]',$locations,explode(',',$shipping->location_id),array('class' => 'form-control','data-toggle'=>'select','multiple')) !!}
        </div>
    </div>
</div>
<div class="text-right">
    {{Form::submit(__('Update'),array('class'=>'btn btn-sm btn-primary rounded-pill'))}}
</div>
{{Form::close()}}

resources/views/shipping/index.blade.php
@extends('layouts.admin')
@section('page-title')
    {{__('Shipping')}}
@endsection
@section('content')
    <div class="card">
        <ul class="nav nav-tabs nav-overflow profile-tab-list" role="tablist">
            <li class="nav-item ml-4">
                <a href="#location" id="location_tab" class="nav-link active" data-toggle="tab" role="tab" aria-controls="home" aria-selected="true">
                    <i class="fas fa-location-arrow mr-2"></i>{{__('Location')}}
                </a>
            </li>
            <li class="nav-item ml-4">
                <a href="#shipping" id="shipping_tab" class="nav-link" data-toggle="tab" role="tab" aria-controls="home" aria-selected="true">
                    <i class="fas fa-shipping-fast mr-2"></i>
                    {{__('Shipping')}}
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade show active" id="location" role="tabpanel" aria-labelledby="orders-tab">
                <!-- Table -->
                <div class="table-responsive">
                    <div class="employee_menu view_employee">
                        <div class="card-header actions-toolbar border-0">
                            <div class="row justify-content-between align-items-center">
                                <div class="col">
                                    <h6 class="d-inline-block mb-0 text-capitalize">{{__('Location')}}</h6>
                                </div>
                                <div class="col text-right">
                                    <div class="actions">
                                        <div class="rounded-pill d-inline-block search_round">
                                            <div class="input-group input-group-sm input-group-merge input-group-flush">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text bg-transparent"><i class="fas fa-search"></i></span>
                                                </div>
                                                <input type="text" id="user_keyword" class="form-control form-control-flush search-user" placeholder="{{__('Search Location')}}">
                                            </div>
                                        </div>
                                        <a href="#" data-size="lg" data-url="{{ route('location.create') }}" data-ajax-popup="true" data-title="{{__('Create New Location')}}" class="btn btn-sm btn-primary btn-icon-only rounded-circle">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Table -->
                        <div class="table-responsive">
                            <table class="table align-items-center employee_tableese">
                                <thead>
                                <tr>
                                    <th scope="col" class="sort" data-sort="name">{{__('Name')}}</th>
                                    <th scope="col" class="sort" data-sort="name">{{__('Created At')}}</th>
                                    <th class="text-right">{{__('Action')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($locations as $location)
                                    <tr data-name="{{$location->name}}">
                                        <td class="sorting_1">{{$location->name}}</td>
                                        <td class="sorting_1">{{\App\Utility::dateFormat($location->created_at)}}</td>
                                        <td class="action text-right">
                                            <a href="#" data-size="lg" data-url="{{ route('location.edit',$location->id) }}" data-toggle="tooltip" data-original-title="{{__('Edit')}}" data-ajax-popup="true" data-title="{{__('Edit type')}}" class="action-item"> <i class="far fa-edit"></i>
                                            </a>
                                            <a href="#" class="action-item" data-toggle="tooltip" data-original-title="{{__('Delete')}}" data-confirm="{{__('Are You Sure?').' | '.__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="document.getElementById('delete-form-{{$location->id}}').submit();">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['location.destroy', $location->id],'id'=>'delete-location-form-'.$location->id]) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <div class="tab-pane" id="shipping" role="tabpanel" aria-labelledby="orders-tab">
                <div class="table-responsive">
                    <div class="employee_menu view_employee">
                        <div class="card-header actions-toolbar border-0">
                            <div class="row justify-content-between align-items-center">
                                <div class="col">
                                    <h6 class="d-inline-block mb-0 text-capitalize">{{__('Shipping')}}</h6>
                                </div>
                                <div class="col text-right">
                                    <div class="actions">
                                        <div class="rounded-pill d-inline-block search_round">
                                            <div class="input-group input-group-sm input-group-merge input-group-flush">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text bg-transparent"><i class="fas fa-search"></i></span>
                                                </div>
                                                <input type="text" id="user_keyword" class="form-control form-control-flush search-user" placeholder="{{__('Search Shipping')}}">
                                            </div>
                                        </div>
                                        <a href="#" data-size="lg" data-url="{{ route('shipping.create') }}" data-ajax-popup="true" data-title="{{__('Create New Shipping')}}" class="btn btn-sm btn-primary btn-icon-only rounded-circle">
                                            <i class="fa fa-plus"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Table -->
                        <div class="table-responsive">
                            <table class="table align-items-center employee_tableese">
                                <thead>
                                <tr>
                                    <th scope="col" class="sort" data-sort="name">{{__('Name')}}</th>
                                    <th scope="col" class="sort" data-sort="name">{{__('Price')}}</th>
                                    <th scope="col" class="sort" data-sort="name">{{__('Location')}}</th>
                                    <th scope="col" class="sort" data-sort="name">{{__('Created At')}}</th>
                                    <th class="text-right">{{__('Action')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($shippings as $shipping)
                                    <tr data-name="{{$shipping->name}}">
                                        <td class="sorting_1">{{$shipping->name}}</td>
                                        <td class="sorting_1">{{\App\Utility::priceFormat($shipping->price)}}</td>
                                        <td class="sorting_1">{{!empty($shipping->locationName()) ? $shipping->locationName() :'-'}}</td>
                                        <td class="sorting_1">{{\App\Utility::dateFormat($shipping->created_at)}}</td>
                                        <td class="action text-right">
                                            <a href="#" data-size="lg" data-url="{{ route('shipping.edit',$shipping->id) }}" data-toggle="tooltip" data-original-title="{{__('Edit')}}" data-ajax-popup="true" data-title="{{__('Edit type')}}" class="action-item"> <i class="far fa-edit"></i>
                                            </a>
                                            <a href="#" class="action-item" data-toggle="tooltip" data-original-title="{{__('Delete')}}" data-confirm="{{__('Are You Sure?').' | '.__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="document.getElementById('delete-form-{{$shipping->id}}').submit();">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                            {!! Form::open(['method' => 'DELETE', 'route' => ['shipping.destroy', $shipping->id],'id'=>'delete-form-'.$shipping->id]) !!}
                                            {!! Form::close() !!}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script-page')
    <script>
        $(document).ready(function () {
            $(document).on('keyup', '.search-user', function () {
                var value = $(this).val();
                $('.employee_tableese tbody>tr').each(function (index) {
                    var name = $(this).attr('data-name');
                    if (name.includes(value)) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                });
            });
        });
    </script>
@endpush