routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/login/{lang?}', 'Auth\LoginController@showLoginForm')->name('login');

Route::get('/password/resets/{lang?}', 'Auth\LoginController@showLinkRequestForm')->name('change.langPass');

Route::get(
    '/', [
           'as' => 'dashboard',
           'uses' => 'DashboardController@index',
       ]
)->middleware(
    [
        'XSS',
    ]
);
Route::get(
    '/dashboard', [
                    'as' => 'dashboard',
                    'uses' => 'DashboardController@index',
                ]
)->middleware(
    [

        'XSS',
        'auth',
    ]
);

Route::group(['middleware' => ['auth', 'XSS']], function (){
    Route::get('change-language/{lang}', 'LanguageController@changeLanquage')->name('change.language')->middleware(['auth', 'XSS']);
    Route::get('manage-language/{lang}', 'LanguageController@manageLanguage')->name('manage.language')->middleware(['auth', 'XSS']);
    Route::post('store-language-data/{lang}', 'LanguageController@storeLanguageData')->name('store.language.data')->middleware(['auth', 'XSS']);
    Route::get('create-language', 'LanguageController@createLanguage')->name('create.language')->middleware(['auth', 'XSS']);
    Route::post('store-language', 'LanguageController@storeLanguage')->name('store.language')->middleware(['auth', 'XSS']);

    Route::delete('/lang/{lang}', 'LanguageController@destroyLang')->name('lang.destroy')->middleware(['auth', 'XSS']);
});

Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ], function (){
    Route::resource('stores', 'StoreController');
    Route::post('store-setting/{id}', 'StoreController@savestoresetting')->name('settings.store');
}
);
Route::get('change-language-store/{slug?}/{lang}', 'LanguageController@changeLanquageStore')->name('change.languagestore')->middleware(['XSS']);
Route::get('/change/mode',['as' => 'change.mode','uses' =>'DashboardController@changeMode']);

Route::get('profile', 'DashboardController@profile')->name('profile')->middleware(
    [
        'auth',
        'XSS',
    ]
);
Route::put('change-password', 'DashboardController@updatePassword')->name('update.password');
Route::put('edit-profile', 'DashboardController@editprofile')->name('update.account')->middleware(
    [
        'auth',
        'XSS',
    ]
);


Route::get('storeanalytic', 'StoreAnalytic@index')->middleware('auth')->name('storeanalytic')->middleware(['XSS']);

Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::post('business-setting', 'SettingController@saveBusinessSettings')->name('business.setting');
    Route::post('company-setting', 'SettingController@saveCompanySettings')->name('company.setting');
    Route::post('email-setting', 'SettingController@saveEmailSettings')->name('email.setting');
    Route::post('system-setting', 'SettingController@saveSystemSettings')->name('system.setting');
    Route::post('pusher-setting', 'SettingController@savePusherSettings')->name('pusher.setting');
    Route::get('test-mail', 'SettingController@testMail')->name('test.mail');
    Route::post('test-mail', 'SettingController@testSendMail')->name('test.send.mail');
    Route::get('settings', 'SettingController@index')->name('settings');
    Route::post('payment-setting', 'SettingController@savePaymentSettings')->name('payment.setting');
    Route::post('owner-payment-setting/{id}', 'SettingController@saveOwnerPaymentSettings')->name('owner.payment.setting');
    Route::post('owner-email-setting/{slug?}', 'SettingController@saveOwneremailSettings')->name('owner.email.setting');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('product_categorie', 'ProductCategorieController');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('product_tax', 'ProductTaxController');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('shipping', 'ShippingController');
}
);
Route::resource('location', 'LocationController')->middleware(['auth', 'XSS']);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::resource('orders', 'OrderController');
}
);
Route::group(
    [
        'middleware' => [
            'XSS',
        ],
    ], function (){
    Route::resource('rating', 'RattingController');
    Route::post('rating_view', 'RattingController@rating_view')->name('rating.rating_view');
    Route::get('rating/{slug?}/product/{id}', 'RattingController@rating')->name('rating');
    Route::post('stor_rating/{slug?}/product/{id}', 'RattingController@stor_rating')->name('stor_rating');
    Route::post('edit_rating/product/{id}', 'RattingController@edit_rating')->name('edit_rating');
}
);
Route::group(
    [
        'middleware' => [
            'XSS',
        ],
    ], function (){
    Route::resource('subscriptions', 'SubscriptionController');
    Route::POST('subscriptions/{id}', 'SubscriptionController@store_email')->name('subscriptions.store_email');
}
);
Route::group(
    [
        'middleware' => [
            'auth',
            'XSS',
        ],
    ], function (){
    Route::get('/product-variants/create',['as' => 'product.variants.create','uses' =>'ProductController@productVariantsCreate']);
    Route::get('/get-product-variants-possibilities',['as' => 'get.product.variants.possibilities','uses' =>'ProductController@getProductVariantsPossibilities']);
    Route::get('product/grid', 'ProductController@grid')->name('product.grid');
    Route::resource('product', 'ProductController');
    Route::delete('product/{id}/delete', 'ProductController@fileDelete')->name('products.file.delete');
    Route::post('product/{id}/update', 'ProductController@productUpdate')->name('products.update');
}
);
Route::get('get-products-variant-quantity',['as' => 'get.products.variant.quantity','uses' =>'ProductController@getProductsVariantQuantity']);
Route::group(
    [
        'middleware' => [
            'auth',
        ],
    ], function (){
    //    Route::get('store-grid/grid', 'StoreController@grid')->name('store-grid.grid');
    Route::resource('store-resource', 'StoreController');
}
);
Route::get('/store-change/{id}','StoreController@changeCurrantStore')->name('change_store')->middleware(['auth','XSS']);


Route::get('store/{slug?}', 'StoreController@storeSlug')->name('store.slug');
Route::get('user-cart-item/{slug?}/cart', 'StoreController@StoreCart')->name('store.cart');
Route::get('user-address/{slug?}/useraddress', 'StoreController@userAddress')->name('user-address.useraddress');
Route::get('store-payment/{slug?}/userpayment', 'StoreController@userPayment')->name('store-payment.payment');
Route::get('store/{slug?}/product/{id}', 'StoreController@productView')->name('store.product.product_view');
Route::post('user-product_qty/{slug?}/product/{id}/{variant_id?}', 'StoreController@productqty')->name('user-product_qty.product_qty');
Route::post('customer/{slug}', 'StoreController@customer')->name('store.customer');
Route::post('user-location/{slug}/location/{id}', 'StoreController@UserLocation')->name('user.location');
Route::post('user-shipping/{slug}/shipping/{id}', 'StoreController@UserShipping')->name('user.shipping');
Route::post('save-rating/{slug}', 'StoreController@saverating')->name('store.saverating');
Route::delete('delete_cart_item/{slug}/product/{id}/{team_member?}/{variant_id?}', 'StoreController@delete_cart_item')->name('delete.cart_item');

Route::get('store-complete/{slug?}/{id}', 'StoreController@complete')->name('store-complete.complete');

Route::post('add-to-cart/{slug?}/{id}/{variant_id?}', 'StoreController@addToCart')->name('user.addToCart');
Route::DELETE('ownerstore-delete/{id}', 'StoreController@ownerstoredestroy')->name('ownerstore.destroy');

Route::get('getMembers/{slug}', 'StoreController@getMembers')->name('user.getMembers');
Route::post('saveMember/{slug}', 'StoreController@storeMember')->name('user.storeMember');

Route::post('payment-setting', 'SettingController@savePaymentSettings')->name('payment.setting');

Route::group(['middleware' => ['XSS']], function (){
    Route::get('order', 'StripePaymentController@index')->name('order.index');
    Route::get('/stripe/{code}', 'StripePaymentController@stripe')->name('stripe');
    Route::post('/stripe/{slug?}', 'StripePaymentController@stripePost')->name('stripe.post');
});

Route::post('pay-with-paypal/{slug?}', 'PaypalController@PayWithPaypal')->name('pay.with.paypal')->middleware(['XSS']);

Route::get('{id}/get-payment-status{slug?}', 'PaypalController@GetPaymentStatus')->name('get.payment.status')->middleware(['XSS']);

Route::get('{slug?}/order/{id}', 'StoreController@userorder')->name('user.order');

Route::post('{slug?}/whatsapp', 'StoreController@whatsapp')->name('user.whatsapp');
Route::post('{slug?}/cod', 'StoreController@cod')->name('user.cod');
Route::post('{slug?}/bank_transfer', 'StoreController@bank_transfer')->name('user.bank_transfer');

Route::get('qr-code', function () {
    return QrCode::generate();
});

resources/views/partials/admin/content.blade.php
<div class="page-title">
    <div class="row justify-content-between align-items-center">
        <div class="col-auto mb-md-0">
            @yield('title')
        </div>
        <div class="col">
            @yield('filter')
        </div>
        <div class="col-auto">
            @yield('action-btn')
        </div>
    </div>
</div>
@yield('content')

resources/views/partials/admin/footer.blade.php
<script src="{{ asset('assets/js/site.core.js')}}"></script>
<!-- Page JS -->
<script src="{{ asset('assets/libs/dropzone/dist/min/dropzone.min.js')}}"></script>
<script src="{{ asset('assets/libs/progressbar.js/dist/progressbar.min.js')}}"></script>
<script src="{{ asset('assets/libs/apexcharts/dist/apexcharts.min.js')}}"></script>

<script src="{{ asset('assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset('assets/libs/bootstrap-notify/bootstrap-notify.min.js')}}"></script>
<script src="{{ asset('assets/libs/select2/dist/js/select2.min.js')}}"></script>
<script src="{{ asset('assets/libs/moment/min/moment.min.js')}}"></script>
<script src="{{ asset('assets/libs/@fancyapps/fancybox/dist/jquery.fancybox.min.js')}}"></script>
<script src="{{ asset('assets/libs/fullcalendar/dist/fullcalendar.min.js')}}"></script>
<script src="{{ asset('assets/libs/flatpickr/dist/flatpickr.min.js')}}"></script>
<script src="{{ asset('assets/libs/quill/dist/quill.min.js')}}"></script>
<script src="{{ asset('assets/libs/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js')}}"></script>
<script src="{{ asset('assets/libs/autosize/dist/autosize.min.js')}}"></script>
<!-- Site JS -->
<script src="{{ asset('assets/js/site.js')}}"></script>

<script src="{{ asset('assets/js/letter.avatar.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/custom.js')}}"></script>


@if(Session::has('success'))
    <script>
        show_toastr('{{__('Success')}}', '{!! session('success') !!}', 'success');
    </script>
    {{ Session::forget('success') }}
@endif
@if(Session::has('error'))
    <script>
        show_toastr('{{__('Error')}}', '{!! session('error') !!}', 'error');
    </script>
    {{ Session::forget('error') }}
@endif
@stack('script-page')
<div class="modal fade" id="commonModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div>
                <h4 class="h4 font-weight-400 float-left modal-title" id="exampleModalLabel"></h4>
                <a href="#" class="more-text widget-text float-right close-icon" data-dismiss="modal" aria-label="Close">{{__('Close')}}</a>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

resources/views/partials/admin/head.blade.php
@php
    $logo=asset(Storage::url('uploads/logo/'));
    $favicon=\App\Utility::getValByName('favicon');

@endphp
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="StoreGo - Business Sales CRM">
    <meta name="author" content="Rajodiya Infotech">


    <title>@yield('page-title') - {{(\App\Utility::getValByName('title_text')) ? \App\Utility::getValByName('title_text') : config('app.name', 'StoreGo')}}</title>
    @if(!empty($favicon))
        <link rel="icon" href="{{asset(Storage::url('uploads/logo/'.$favicon))}}" type="image/png">
    @else
        <link rel="icon" href="{{asset(Storage::url('uploads/logo/favicon.png'))}}" type="image/png">
    @endif
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="stylesheet" href="{{ asset('assets/libs/@fortawesome/fontawesome-free/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/libs/fullcalendar/dist/fullcalendar.min.css')}}">

    <link rel="stylesheet" href="{{ asset('assets/libs/animate.css/animate.min.css')}}" id="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/libs/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{asset('assets/libs/@fancyapps/fancybox/dist/jquery.fancybox.min.css')}}">
    <link rel="stylesheet" href="{{ asset('assets/css/site.css')}}" id="stylesheet">

    <link rel="stylesheet" href="{{ asset('assets/css/jquery.dataTables.min.css')}}">

        <link rel="stylesheet" href="{{ asset('assets/css/site-'.Auth::user()->mode.'.css') }}" id="stylesheet">
    <link rel="stylesheet" href="{{ asset('assets/css/custom.css')}}" id="stylesheet')}}">
    <script type="text/javascript" src="{{ asset('assets/js/jquery-1.11.1.min.js')}}"></script>

    @stack('css-page')
</head>

resources/views/partials/admin/header.blade.php
@php
    $logo=\App\Utility::getValByName('logo');
    $logo_path=asset(Storage::url('uploads/logo/'));
    $favicon=\App\Utility::getValByName('favicon');
    $users=\Auth::user();
    $currantLang = $users->currentLanguages();
@endphp
<nav class="navbar navbar-main navbar-expand-lg navbar-dark bg-primary navbar-border" id="navbar-main">
    <div class="container-fluid">
        <!-- Brand + Toggler (for mobile devices) -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main-collapse" aria-controls="navbar-main-collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- User's navbar -->
        <div class="navbar-user d-lg-none ml-auto">
            <ul class="navbar-nav flex-row align-items-center">
                <li class="nav-item dropdown dropdown-animate">
                    <a class="nav-link pr-lg-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="avatar avatar-sm rounded-circle">
                      <img alt="Image placeholder" src="{{asset(Storage::url('uploads/profile/avatar.png'))}}">
                  </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right dropdown-menu-arrow">
                        <h6 class="dropdown-header px-0">Hi, {{\Auth::user()->name}}!</h6>
                        <a href="{{route('profile')}}" class="dropdown-item">
                            <i class="fas fa-user"></i>
                            <span>{{__('My profile')}}</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();" class="dropdown-item has-icon text-danger">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>{{__('Logout')}}</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
        <!-- Navbar nav -->
        <div class="collapse navbar-collapse navbar-collapse-fade" id="navbar-main-collapse">
            <ul class="navbar-nav align-items-lg-center">
                <!-- Overview  -->
                <li class="nav-item">
                    <div class="d-flex align-items-center mr-5">
                        <a class="navbar-brand" href="{{ route('dashboard') }}">
                            @if(!empty($logo))
                                <img src="{{asset(Storage::url('uploads/logo/'.$logo))}}" class="navbar-brand-img custom-logo" alt="{{ __('Company Logo') }}">
                            @else
                                <img src="{{asset(Storage::url('uploads/logo/logo.png'))}}" class="navbar-brand-img custom-logo" alt="{{ __('Company Logo') }}">
                            @endif
                        </a>
                    </div>
                </li>
                <li class="border-top opacity-2 my-2"></li>
                <!-- Home  -->
                <li class="nav-item dropdown dropdown-animate" data-toggle="hover">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{__('Dashboard')}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow p-lg-0">
                        <!-- Top dropdown menu -->
                        <div class="p-lg-4">
                            <a class="dropdown-item" href="{{route('dashboard')}}">
                                {{__('Dashboard')}}
                            </a>
                            <a class="dropdown-item" href="{{route('storeanalytic')}}">
                                {{__('Store Analytics')}}
                            </a>
                        </div>
                    </div>
                </li>
                <!-- Application menu -->
                <li class="nav-item dropdown dropdown-animate" data-toggle="hover">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{__('Shop')}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow p-lg-0">
                        <!-- Top dropdown menu -->
                        <div class="p-lg-4">
                            <a class="dropdown-item" href="{{route('product.index')}}">
                                {{__('Products')}}
                            </a>
                            <a href="{{route('product_categorie.index')}}" class="dropdown-item" role="button">
                                {{__('Product Categories')}}
                            </a>
                            <a href="{{route('product_tax.index')}}" class="dropdown-item" role="button">
                                {{__('Product Tax')}}
                            </a>
                            <a href="{{route('subscriptions.index')}}" class="dropdown-item" role="button">
                                {{__('Subscriber')}}
                            </a>
                            <a href="{{route('shipping.index')}}" class="dropdown-item" role="button">
                                {{__('Shipping')}}
                            </a>
                        </div>
                    </div>
                </li>
                <li class="nav-item">
                    <a href="{{route('orders.index')}}" class="nav-link">
                        <span>{{__('Orders')}}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('manage.language',[$currantLang])}}" class="nav-link {{ (Request::segment(1) == 'manage-language')?'active':''}}">
                        {{__('Language')}}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('settings')}}">
                        {{__('Store Setting')}}
                    </a>
                </li>
                <li class="border-top opacity-2 my-2"></li>
            </ul>
            <!-- Right menu -->
            <ul class="navbar-nav ml-lg-auto align-items-center d-none d-lg-flex wsdb vhdasgvc">
                <li class="nav-item dropdown dropdown-animate">
                    <a class="nav-link pr-lg-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media media-pill align-items-center p-2">
                            @foreach(\Auth::user()->stores as $store)
                                @if(\Auth::user()->current_store == $store->id)
                                    <div class="d-none d-lg-block">
                                        <span class="mb-0 text-sm  font-weight-bold"><img src="{{$logo_path.'/'.(isset($favicon) && !empty($favicon)?$favicon:'favicon.png')}}" type="image" width="20px">{{ $store->name }}</span>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right dropdown-menu-arrow">
                        @foreach(\Auth::user()->stores as $store)
                            @if($store->is_active)
                                <a href="@if(Auth::user()->current_store == $store->id)#@else {{ route('change_store',$store->id) }} @endif" title="{{ $store->name }}" class="dropdown-item notify-item">
                                    @if(Auth::user()->current_store == $store->id)
                                        <i class="fas fa-check"></i>
                                    @endif
                                    <span>{{ $store->name }}</span>
                                </a>
                            @else
                                <a href="#" class="dropdown-item notify-item" title="{{__('Locked')}}">
                                    <i class="fas fa-lock"></i>
                                    <span>{{ $store->name }}</span>
                                    @if(isset($store->pivot->permission))
                                        @if($store->pivot->permission =='Owner')
                                            <span class="badge badge-primary">{{__($store->pivot->permission)}}</span>
                                        @else
                                            <span class="badge badge-secondary">{{__('Shared')}}</span>
                                        @endif
                                    @endif
                                </a>
                            @endif
                        @endforeach
                        <div class="dropdown-divider"></div>
                        @auth('web')
                            @if(Auth::user()->type == 'Owner')
                                <a href="#" data-size="lg" data-url="{{ route('store-resource.create') }}" data-ajax-popup="true" data-title="{{__('Create New Store')}}" class="dropdown-item notify-item">
                                    <i class="fa fa-plus"></i><span>{{ __('Create New Store')}}</span>
                                </a>
                            @endif
                        @endauth
                    </div>
                </li>

                <li class="nav-item dropdown dropdown-animate">
                    <a class="nav-link pr-lg-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media media-pill align-items-center">
                    <span class="avatar rounded-circle">
                      <img alt="Image placeholder" src="{{asset(Storage::url('uploads/profile/avatar.png'))}}">
                    </span>
                            <div class="ml-2 d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{\Auth::user()->name}}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right dropdown-menu-arrow">
                        <h6 class="dropdown-header px-0">Hi, {{\Auth::user()->name}}!</h6>
                        <a href="{{route('profile')}}" class="dropdown-item">
                            <i class="fas fa-user"></i>
                            <span>{{__('My profile')}}</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();" class="dropdown-item has-icon text-danger">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>{{__('Logout')}}</span>
                        </a>
                        <form id="frm-logout" action="{{ route('logout') }}" method="POST" class="d-none">
                            {{ csrf_field() }}
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>